### PR TITLE
Remove patch file; implement hook_datastream_filename_alter(); update…

### PR DESCRIPTION
**Pull request by patdunlavey**
… documentation

Why:

* A PR has been created on the islandora module to support altering downloadable filenames. When that is accepted, then this change eliminates the need for users to patch islandora.

This change addresses the need by:

* Removing the patch file
* Switching from hook_create_datastream_filename() to hook_datastream_filename_alter
* Updating the docs to no longer provide instructions for applying the patch file.

Reference Links:

* https://jira.duraspace.org/browse/ISLANDORA-1748
* https://github.com/ulsdevteam/islandora_datastream_filenamer/issues/1
* https://github.com/Islandora/islandora/pull/706

### CODE REVIEW

**Comment by patdunlavey** [comment]
Hi Brian. I changed the hook name to reflect a suggestion by Diego on the islandora core pull request.

**Comment by patdunlavey** [comment]
The core islandora pull request has been accepted. 24 hours to merge. 

https://github.com/Islandora/islandora/pull/706#issuecomment-390994136

**Review by wgilling — APPROVED** [review]
Looks ok --- merging and testing this pull request is painful especially when our islandora branch conflicted with the required pull request on that module.

**Comment by patdunlavey** [comment]
Hi Brian. The [PR](https://github.com/Islandora/islandora/pull/706) to Islandora core was merged a couple weeks ago. Any way we can get this merged/closed?

**Comment by wgilling** [comment]
Closed - thanks and very good work on this! :)

**Comment by patdunlavey** [comment]
Thanks so much Brian!

**Pull request merged**
